import { Opportunity } from "./types";

export const mockOpportunities: Opportunity[] = [
  {
    id: "1",
    title: "Senior Frontend Engineer",
    company: "Northwind Studio",
    field: "Tech",
    location: "Helsinki",
    status: "expected_soon",
    insiderNote:
      "Their lead frontend dev just gave notice. Team is quietly scoping a replacement before the public posting goes up.",
    source: "Former colleague, now at Northwind",
    postedAt: "2026-09-28",
  },
  {
    id: "2",
    title: "Growth Marketing Lead",
    company: "Fjord Analytics",
    field: "Marketing",
    location: "Remote (EU)",
    status: "potential",
    insiderNote:
      "Series A just closed. Founder mentioned wanting a dedicated growth hire within the quarter during a podcast interview.",
    source: "Public podcast + LinkedIn signal",
    postedAt: "2026-09-25",
  },
  {
    id: "3",
    title: "Guest Experience Manager",
    company: "Lumi Hotels",
    field: "Tourism",
    location: "Rovaniemi",
    status: "open",
    insiderNote:
      "Internal job board posting went live this morning, two days before it hits external sites.",
    source: "Internal referral",
    postedAt: "2026-10-01",
  },
  {
    id: "4",
    title: "Backend Engineer (Payments)",
    company: "Tide & Co",
    field: "Tech",
    location: "Espoo",
    status: "expected_soon",
    insiderNote:
      "New payments product launching in Q1. Engineering manager has been informally asking around for referrals.",
    source: "Engineering manager, direct message",
    postedAt: "2026-09-30",
  },
  {
    id: "5",
    title: "Social Media Strategist",
    company: "Birch & Pine Co.",
    field: "Marketing",
    location: "Helsinki",
    status: "closed",
    insiderNote:
      "Role was filled internally last week, but may reopen if the chosen candidate doesn't relocate in time.",
    source: "HR contact",
    postedAt: "2026-09-18",
  },
  {
    id: "6",
    title: "Junior Data Analyst",
    company: "Polar Insights",
    field: "Tech",
    location: "Turku",
    status: "potential",
    insiderNote:
      "Team is overloaded and has mentioned headcount requests in two consecutive all-hands meetings.",
    source: "Current employee",
    postedAt: "2026-09-29",
  },
  {
    id: "7",
    title: "Tour Operations Coordinator",
    company: "Aurora Trails",
    field: "Tourism",
    location: "Rovaniemi",
    status: "open",
    insiderNote:
      "Posted on their careers page but not yet syndicated to job boards — a short early window before volume applications start.",
    source: "Company careers page",
    postedAt: "2026-10-02",
  },
  {
    id: "8",
    title: "Product Manager",
    company: "Nordic Design Co",
    field: "Product",
    location: "Helsinki",
    status: "potential",
    insiderNote: "Looking to expand their product team for the new platform launch.",
    source: "LinkedIn update",
    postedAt: "2026-10-01",
  },
  {
    id: "9",
    title: "UX/UI Designer",
    company: "Creative Hub",
    field: "Design",
    location: "Helsinki",
    status: "expected_soon",
    insiderNote: "Design team mentioned they need more hands for upcoming project.",
    source: "Design community",
    postedAt: "2026-09-28",
  },
  {
    id: "10",
    title: "Business Development Manager",
    company: "Scale Partners",
    field: "Business",
    location: "Remote (EU)",
    status: "potential",
    insiderNote: "Expanding into new markets and looking for strategic partnerships.",
    source: "Founder interview",
    postedAt: "2026-09-27",
  },
  {
    id: "11",
    title: "Content Strategist",
    company: "Digital Voices",
    field: "Content",
    location: "Turku",
    status: "open",
    insiderNote: "Content team restructuring, new roles being created.",
    source: "Internal referral",
    postedAt: "2026-10-01",
  },
  {
    id: "12",
    title: "HR Specialist",
    company: "People First Ltd",
    field: "HR",
    location: "Helsinki",
    status: "expected_soon",
    insiderNote: "Growing team, planning to hire for people operations.",
    source: "HR contact",
    postedAt: "2026-09-29",
  },
  {
    id: "13",
    title: "Sales Executive",
    company: "Enterprise Solutions",
    field: "Sales",
    location: "Remote (EU)",
    status: "potential",
    insiderNote: "New sales region opening up in Q1 2027.",
    source: "Sales lead referral",
    postedAt: "2026-09-26",
  },
  {
    id: "14",
    title: "Operations Coordinator",
    company: "Logistics Plus",
    field: "Operations",
    location: "Espoo",
    status: "open",
    insiderNote: "Expansion of operations team in preparation for growth.",
    source: "Company announcement",
    postedAt: "2026-10-02",
  },
];
